kind: pipeline
type: docker
name: build

steps:
- name: test
  image: golang:1.20
  commands:
  - go test -v -race -skip '^TestE2E' ./...

- name: build
  image: golang:1.20
  environment:
    GOOS: linux
    GOARCH: amd64 
  commands:
  - go build -ldflags "-s -w" -o build/ev ./cmd/ev 

- name: compress
  image: gruebel/upx:latest
  commands: 
    - upx --best --lzma -o ev build/ev

---
kind: pipeline
type: docker
name: default

steps:
- name: deploy
  image: plugins/ansible:3
  settings:
    playbook: .ansible/playbook.yml
    inventory: .ansible/inventory
    become: true
    become_method: sudo
    user: deploy
    private_key: 
      from_secret: drone_ssh

trigger:
  event:
  - promote
  target:
  - lavana
